const express = require('express')
const { createUser, getUser, deleteUser, updateUser, registerUser, loginUser } = require('../controller/user.controller')
const { authMiddleware } = require('../middleware/auth.middleware')
const { validate } = require('express-validation')
const { addUser, userId, updateUserValidation, } = require('../validations/user.validation')
const router = express.Router()
const { upload } = require('../middleware/multer.middleware')
router.post('/adduser', validate(addUser), createUser)
router.get('/getuser', authMiddleware, getUser)
router.delete('/deleteuser/:id', authMiddleware, deleteUser)
router.put('/updateuser/:id', validate(userId), upload.single('profile'), validate(updateUserValidation), authMiddleware, updateUser)

router.post('/register', registerUser)
router.post('/login', loginUser)
module.exports = router